import { Component } from '@angular/core';
import * as i0 from "@angular/core";
export class FooterComponent {
    static ɵfac = function FooterComponent_Factory(__ngFactoryType__) { return new (__ngFactoryType__ || FooterComponent)(); };
    static ɵcmp = /*@__PURE__*/ i0.ɵɵdefineComponent({ type: FooterComponent, selectors: [["app-footer"]], decls: 65, vars: 0, consts: [[1, "footer"], [1, "footer-container"], [1, "footer-left"], [1, "logo"], [1, "logo-box"], [1, "tagline"], [1, "social-icons"], [1, "footer-links"], ["routerLink", "/journey"], ["routerLink", "/universities"], ["routerLink", "/finance"], ["routerLink", "/tools"], ["routerLink", "/checklists"], [1, "footer-bottom"], [1, "badges"]], template: function FooterComponent_Template(rf, ctx) { if (rf & 1) {
            i0.ɵɵdomElementStart(0, "footer", 0)(1, "div", 1)(2, "div", 2)(3, "div", 3)(4, "div", 4);
            i0.ɵɵtext(5, "BP");
            i0.ɵɵdomElementEnd();
            i0.ɵɵdomElementStart(6, "div")(7, "h2");
            i0.ɵɵtext(8, "Bidesh Padhna");
            i0.ɵɵdomElementEnd();
            i0.ɵɵdomElementStart(9, "p", 5);
            i0.ɵɵtext(10, " A free platform helping Nepali students navigate every step of studying abroad \u2014 from shortlisting to visa. ");
            i0.ɵɵdomElementEnd()()();
            i0.ɵɵdomElementStart(11, "div", 6)(12, "span");
            i0.ɵɵtext(13, "\uD83D\uDC26");
            i0.ɵɵdomElementEnd();
            i0.ɵɵdomElementStart(14, "span");
            i0.ɵɵtext(15, "\uD83D\uDCAC");
            i0.ɵɵdomElementEnd();
            i0.ɵɵdomElementStart(16, "span");
            i0.ɵɵtext(17, "\u25B6\uFE0F");
            i0.ɵɵdomElementEnd()()();
            i0.ɵɵdomElementStart(18, "div", 7)(19, "h3");
            i0.ɵɵtext(20, "PLATFORM");
            i0.ɵɵdomElementEnd();
            i0.ɵɵdomElementStart(21, "a", 8);
            i0.ɵɵtext(22, "Journey Steps");
            i0.ɵɵdomElementEnd();
            i0.ɵɵdomElementStart(23, "a", 9);
            i0.ɵɵtext(24, "Universities");
            i0.ɵɵdomElementEnd();
            i0.ɵɵdomElementStart(25, "a", 10);
            i0.ɵɵtext(26, "Finance Planner");
            i0.ɵɵdomElementEnd();
            i0.ɵɵdomElementStart(27, "a", 11);
            i0.ɵɵtext(28, "Smart Tools");
            i0.ɵɵdomElementEnd();
            i0.ɵɵdomElementStart(29, "a", 12);
            i0.ɵɵtext(30, "Checklists");
            i0.ɵɵdomElementEnd()();
            i0.ɵɵdomElementStart(31, "div", 7)(32, "h3");
            i0.ɵɵtext(33, "RESOURCES");
            i0.ɵɵdomElementEnd();
            i0.ɵɵdomElementStart(34, "a");
            i0.ɵɵtext(35, "Blog");
            i0.ɵɵdomElementEnd();
            i0.ɵɵdomElementStart(36, "a");
            i0.ɵɵtext(37, "Video Guides");
            i0.ɵɵdomElementEnd();
            i0.ɵɵdomElementStart(38, "a");
            i0.ɵɵtext(39, "Templates");
            i0.ɵɵdomElementEnd();
            i0.ɵɵdomElementStart(40, "a");
            i0.ɵɵtext(41, "Community");
            i0.ɵɵdomElementEnd();
            i0.ɵɵdomElementStart(42, "a");
            i0.ɵɵtext(43, "FAQs");
            i0.ɵɵdomElementEnd()();
            i0.ɵɵdomElementStart(44, "div", 7)(45, "h3");
            i0.ɵɵtext(46, "COMPANY");
            i0.ɵɵdomElementEnd();
            i0.ɵɵdomElementStart(47, "a");
            i0.ɵɵtext(48, "About");
            i0.ɵɵdomElementEnd();
            i0.ɵɵdomElementStart(49, "a");
            i0.ɵɵtext(50, "Contact Us");
            i0.ɵɵdomElementEnd();
            i0.ɵɵdomElementStart(51, "a");
            i0.ɵɵtext(52, "Privacy Policy");
            i0.ɵɵdomElementEnd();
            i0.ɵɵdomElementStart(53, "a");
            i0.ɵɵtext(54, "Terms of Use");
            i0.ɵɵdomElementEnd();
            i0.ɵɵdomElementStart(55, "a");
            i0.ɵɵtext(56, "Feedback");
            i0.ɵɵdomElementEnd()()();
            i0.ɵɵdomElementStart(57, "div", 13)(58, "p");
            i0.ɵɵtext(59, "\u00A9 2026 Bidesh Padhna. Free for every Nepali student.");
            i0.ɵɵdomElementEnd();
            i0.ɵɵdomElementStart(60, "div", 14)(61, "span");
            i0.ɵɵtext(62, "Made in Nepal \uD83C\uDDF3\uD83C\uDDF5");
            i0.ɵɵdomElementEnd();
            i0.ɵɵdomElementStart(63, "span");
            i0.ɵɵtext(64, "100% Free");
            i0.ɵɵdomElementEnd()()()();
        } }, styles: [".footer[_ngcontent-%COMP%] {\n  background-color: #0b1d2a;\n  color: #cbd5e1;\n  padding: 40px 280px;\n  font-family: 'Inter', sans-serif;\n}\n\n.footer-container[_ngcontent-%COMP%] {\n  display: grid;\n  grid-template-columns: 2fr 1fr 1fr 1fr;\n  gap: 104px;\n}\n\n.logo[_ngcontent-%COMP%] {\n  display: flex;\n  gap: 15px;\n  align-items: flex-start;\n}\n\n.logo-box[_ngcontent-%COMP%] {\n  margin-top: 20px;\n  background: linear-gradient(135deg, #34d399, #10b981);\n  color: white;\n  font-weight: bold;\n  padding: 10px 14px;\n  border-radius: 10px;\n}\n\n.tagline[_ngcontent-%COMP%] {\n  font-size: 14px;\n  margin-top: 10px;\n  line-height: 1.6;\n  color: #94a3b8;\n}\n\n.social-icons[_ngcontent-%COMP%] {\n  margin-top: 20px;\n  display: flex;\n  gap: 15px;\n}\n\n.social-icons[_ngcontent-%COMP%]   span[_ngcontent-%COMP%] {\n  background: #1e293b;\n  padding: 10px;\n  border-radius: 8px;\n  cursor: pointer;\n}\n\n.footer-links[_ngcontent-%COMP%]   h3[_ngcontent-%COMP%] {\n  color: #e2e8f0;\n  margin-bottom: 10px;\n  font-size: 14px;\n}\n\n.footer-links[_ngcontent-%COMP%]   a[_ngcontent-%COMP%] {\n  display: block;\n  margin: 6px 0;\n  font-size: 14px;\n  cursor: pointer;\n  color: #94a3b8;\n}\n\n.footer-links[_ngcontent-%COMP%]   a[_ngcontent-%COMP%]:hover {\n  color: white;\n}\n\n.footer-bottom[_ngcontent-%COMP%] {\n  border-top: 1px solid #1e293b;\n  margin-top: 30px;\n  padding-top: 20px;\n  display: flex;\n  justify-content: space-between;\n  align-items: center;\n  font-size: 14px;\n}\n\n.badges[_ngcontent-%COMP%]   span[_ngcontent-%COMP%] {\n  margin-left: 10px;\n  padding: 6px 12px;\n  background: #1e293b;\n  border-radius: 20px;\n}"] });
}
(() => { (typeof ngDevMode === "undefined" || ngDevMode) && i0.ɵsetClassMetadata(FooterComponent, [{
        type: Component,
        args: [{ selector: 'app-footer', template: "<footer class=\"footer\">\n  <div class=\"footer-container\">\n\n    <div class=\"footer-left\">\n      <div class=\"logo\">\n        <div class=\"logo-box\">BP</div>\n        <div>\n          <h2>Bidesh Padhna</h2>\n          <p class=\"tagline\">\n            A free platform helping Nepali students navigate every step of studying abroad \u2014\n            from shortlisting to visa.\n          </p>\n        </div>\n      </div>\n\n      <div class=\"social-icons\">\n        <span>\uD83D\uDC26</span>\n        <span>\uD83D\uDCAC</span>\n        <span>\u25B6\uFE0F</span>\n      </div>\n    </div>\n\n    <div class=\"footer-links\">\n      <h3>PLATFORM</h3>\n      <a routerLink=\"/journey\">Journey Steps</a>\n      <a routerLink=\"/universities\">Universities</a>\n      <a routerLink=\"/finance\">Finance Planner</a>\n      <a routerLink=\"/tools\">Smart Tools</a>\n      <a routerLink=\"/checklists\">Checklists</a>\n    </div>\n\n    <div class=\"footer-links\">\n      <h3>RESOURCES</h3>\n      <a>Blog</a>\n      <a>Video Guides</a>\n      <a>Templates</a>\n      <a>Community</a>\n      <a>FAQs</a>\n    </div>\n\n    <div class=\"footer-links\">\n      <h3>COMPANY</h3>\n      <a>About</a>\n      <a>Contact Us</a>\n      <a>Privacy Policy</a>\n      <a>Terms of Use</a>\n      <a>Feedback</a>\n    </div>\n\n  </div>\n\n  <div class=\"footer-bottom\">\n    <p>\u00A9 2026 Bidesh Padhna. Free for every Nepali student.</p>\n\n    <div class=\"badges\">\n      <span>Made in Nepal \uD83C\uDDF3\uD83C\uDDF5</span>\n      <span>100% Free</span>\n    </div>\n  </div>\n</footer>", styles: [".footer {\n  background-color: #0b1d2a;\n  color: #cbd5e1;\n  padding: 40px 280px;\n  font-family: 'Inter', sans-serif;\n}\n\n.footer-container {\n  display: grid;\n  grid-template-columns: 2fr 1fr 1fr 1fr;\n  gap: 104px;\n}\n\n.logo {\n  display: flex;\n  gap: 15px;\n  align-items: flex-start;\n}\n\n.logo-box {\n  margin-top: 20px;\n  background: linear-gradient(135deg, #34d399, #10b981);\n  color: white;\n  font-weight: bold;\n  padding: 10px 14px;\n  border-radius: 10px;\n}\n\n.tagline {\n  font-size: 14px;\n  margin-top: 10px;\n  line-height: 1.6;\n  color: #94a3b8;\n}\n\n.social-icons {\n  margin-top: 20px;\n  display: flex;\n  gap: 15px;\n}\n\n.social-icons span {\n  background: #1e293b;\n  padding: 10px;\n  border-radius: 8px;\n  cursor: pointer;\n}\n\n.footer-links h3 {\n  color: #e2e8f0;\n  margin-bottom: 10px;\n  font-size: 14px;\n}\n\n.footer-links a {\n  display: block;\n  margin: 6px 0;\n  font-size: 14px;\n  cursor: pointer;\n  color: #94a3b8;\n}\n\n.footer-links a:hover {\n  color: white;\n}\n\n.footer-bottom {\n  border-top: 1px solid #1e293b;\n  margin-top: 30px;\n  padding-top: 20px;\n  display: flex;\n  justify-content: space-between;\n  align-items: center;\n  font-size: 14px;\n}\n\n.badges span {\n  margin-left: 10px;\n  padding: 6px 12px;\n  background: #1e293b;\n  border-radius: 20px;\n}"] }]
    }], null, null); })();
(() => { (typeof ngDevMode === "undefined" || ngDevMode) && i0.ɵsetClassDebugInfo(FooterComponent, { className: "FooterComponent", filePath: "src/app/core/components/site-footer/footer.ts", lineNumber: 8 }); })();
