import { Component } from '@angular/core';
import { Layout } from '../layout/layout';
import * as i0 from "@angular/core";
import * as i1 from "@angular/router";
export class AboutComponent {
    router;
    constructor(router) {
        this.router = router;
    }
    goToContact() {
        this.router.navigate(['/contact']);
    }
    static ɵfac = function AboutComponent_Factory(__ngFactoryType__) { return new (__ngFactoryType__ || AboutComponent)(i0.ɵɵdirectiveInject(i1.Router)); };
    static ɵcmp = /*@__PURE__*/ i0.ɵɵdefineComponent({ type: AboutComponent, selectors: [["app-about"]], decls: 106, vars: 0, consts: [[1, "about-section"], [1, "circle-bg"], [1, "content"], [1, "badge"], [1, "description"], [1, "stats"], [1, "stat"], [1, "bottom-stat"], [1, "scroll-down"], [1, "purpose-section"], [1, "purpose-header"], [1, "purpose-cards"], [1, "card"], [1, "icon"], [1, "card", "highlight"], [1, "tools-section"], [1, "container"], [1, "subtitle"], [1, "grid"], [1, "card", "green"], [1, "card", "yellow"], [1, "card", "blue"], [1, "card", "red"], [1, "card", "purple"], [1, "card", "green2"]], template: function AboutComponent_Template(rf, ctx) { if (rf & 1) {
            i0.ɵɵelementStart(0, "app-layout")(1, "section", 0);
            i0.ɵɵelement(2, "div", 1);
            i0.ɵɵelementStart(3, "div", 2)(4, "div", 3);
            i0.ɵɵtext(5, "\u25CF ABOUT BIDESH PADHNA");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(6, "h1");
            i0.ɵɵtext(7, " We exist so ");
            i0.ɵɵelementStart(8, "span");
            i0.ɵɵtext(9, "no Nepali student");
            i0.ɵɵelementEnd();
            i0.ɵɵelement(10, "br");
            i0.ɵɵtext(11, " has to figure it out alone. ");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(12, "p", 4);
            i0.ɵɵtext(13, " Bidesh Padhna was born from a simple truth \u2014 studying abroad is life-changing, but the process is confusing, expensive, and lonely. We fix that. For free. ");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(14, "div", 5)(15, "div", 6)(16, "h2");
            i0.ɵɵtext(17, "800+");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(18, "p");
            i0.ɵɵtext(19, "STUDENTS GUIDED");
            i0.ɵɵelementEnd()();
            i0.ɵɵelementStart(20, "div", 6)(21, "h2");
            i0.ɵɵtext(22, "8");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(23, "p");
            i0.ɵɵtext(24, "COUNTRIES COVERED");
            i0.ɵɵelementEnd()();
            i0.ɵɵelementStart(25, "div", 6)(26, "h2");
            i0.ɵɵtext(27, "94%");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(28, "p");
            i0.ɵɵtext(29, "VISA SUCCESS RATE");
            i0.ɵɵelementEnd()()();
            i0.ɵɵelementStart(30, "div", 7)(31, "h2");
            i0.ɵɵtext(32, "1200+");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(33, "p");
            i0.ɵɵtext(34, "UNIVERSITIES LISTED");
            i0.ɵɵelementEnd()();
            i0.ɵɵelementStart(35, "div", 8);
            i0.ɵɵtext(36, "\u2193");
            i0.ɵɵelementEnd()()();
            i0.ɵɵelementStart(37, "section", 9)(38, "div", 10)(39, "span", 3);
            i0.ɵɵtext(40, "OUR PURPOSE");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(41, "h2");
            i0.ɵɵtext(42, "Why does Bidesh Padhna exist?");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(43, "p");
            i0.ɵɵtext(44, " Too many bright Nepali students give up on studying abroad because the process feels impossible. We built the platform we wished existed when we were students. ");
            i0.ɵɵelementEnd()();
            i0.ɵɵelementStart(45, "div", 11)(46, "div", 12)(47, "div", 13);
            i0.ɵɵtext(48, "\u23F1\uFE0F");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(49, "h3");
            i0.ɵɵtext(50, "Eliminate confusion");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(51, "p");
            i0.ɵɵtext(52, " The path from \"I want to study abroad\" to \"I have my visa\" has 40+ steps. ");
            i0.ɵɵelementEnd()();
            i0.ɵɵelementStart(53, "div", 14)(54, "div", 13);
            i0.ɵɵtext(55, "\uD83D\uDCB0");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(56, "h3");
            i0.ɵɵtext(57, "Make it free");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(58, "p");
            i0.ɵɵtext(59, " Consultancy fees in Nepal can cost NPR 50,000\u20132,00,000. ");
            i0.ɵɵelementEnd()();
            i0.ɵɵelementStart(60, "div", 12)(61, "div", 13);
            i0.ɵɵtext(62, "\uD83E\uDD1D");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(63, "h3");
            i0.ɵɵtext(64, "Build community");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(65, "p");
            i0.ɵɵtext(66, " Connect with Nepali students already studying abroad. ");
            i0.ɵɵelementEnd()()()();
            i0.ɵɵelementStart(67, "section", 15)(68, "div", 16)(69, "span", 3);
            i0.ɵɵtext(70, "EXPLORE THE PLATFORM");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(71, "h2");
            i0.ɵɵtext(72, "Everything you can do here");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(73, "p", 17);
            i0.ɵɵtext(74, " Six powerful tools, all free, all built for Nepali students going abroad. ");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(75, "div", 18)(76, "div", 19)(77, "h4");
            i0.ɵɵtext(78, "JOURNEY");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(79, "h3");
            i0.ɵɵtext(80, "Step-by-step roadmap");
            i0.ɵɵelementEnd()();
            i0.ɵɵelementStart(81, "div", 20)(82, "h4");
            i0.ɵɵtext(83, "SMART TOOLS");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(84, "h3");
            i0.ɵɵtext(85, "AI SOP maker");
            i0.ɵɵelementEnd()();
            i0.ɵɵelementStart(86, "div", 21)(87, "h4");
            i0.ɵɵtext(88, "UNIVERSITIES");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(89, "h3");
            i0.ɵɵtext(90, "University finder");
            i0.ɵɵelementEnd()();
            i0.ɵɵelementStart(91, "div", 22)(92, "h4");
            i0.ɵɵtext(93, "FINANCE");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(94, "h3");
            i0.ɵɵtext(95, "Cost of living calculator");
            i0.ɵɵelementEnd()();
            i0.ɵɵelementStart(96, "div", 23)(97, "h4");
            i0.ɵɵtext(98, "CHECKLISTS");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(99, "h3");
            i0.ɵɵtext(100, "Document checklists");
            i0.ɵɵelementEnd()();
            i0.ɵɵelementStart(101, "div", 24)(102, "h4");
            i0.ɵɵtext(103, "COMMUNITY");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(104, "h3");
            i0.ɵɵtext(105, "Student forum");
            i0.ɵɵelementEnd()()()()()();
        } }, dependencies: [Layout], styles: ["body[_ngcontent-%COMP%] {\n  margin: 0;\n  font-family: 'Inter', sans-serif;\n}\n\n.container[_ngcontent-%COMP%] {\n  max-width: 1100px;\n  margin: 0 auto;\n  padding: 80px 20px;\n  text-align: center;\n}\n\n\n.about-section[_ngcontent-%COMP%] {\n  position: relative;\n  height: 100vh;\n  background: #0b1c2c;\n  display: flex;\n  justify-content: center;\n  align-items: center;\n  overflow: hidden;\n  color: white;\n  text-align: center;\n}\n\n.circle-bg[_ngcontent-%COMP%] {\n  position: absolute;\n  width: 900px;\n  height: 900px;\n  background: radial-gradient(circle, rgba(0, 255, 200, 0.15), transparent 70%);\n  border-radius: 50%;\n  z-index: 0;\n}\n\n.about-section[_ngcontent-%COMP%]   .content[_ngcontent-%COMP%] {\n  position: relative;\n  z-index: 1;\n  max-width: 900px;\n}\n\n.about-section[_ngcontent-%COMP%]   .badge[_ngcontent-%COMP%] {\n  display: inline-block;\n  padding: 6px 16px;\n  border-radius: 20px;\n  background: rgba(0, 255, 200, 0.1);\n  color: #00d4aa;\n  font-size: 12px;\n  margin-bottom: 20px;\n  letter-spacing: 1px;\n}\n\n.about-section[_ngcontent-%COMP%]   h1[_ngcontent-%COMP%] {\n  font-size: 48px;\n  line-height: 1.3;\n}\n\n.about-section[_ngcontent-%COMP%]   h1[_ngcontent-%COMP%]   span[_ngcontent-%COMP%] {\n  color: #00d4aa;\n}\n\n.description[_ngcontent-%COMP%] {\n  margin: 20px 0;\n  color: #b0bec5;\n}\n\n.stats[_ngcontent-%COMP%] {\n  display: flex;\n  justify-content: center;\n  gap: 60px;\n  margin-top: 30px;\n}\n\n.stat[_ngcontent-%COMP%]   h2[_ngcontent-%COMP%] {\n  font-size: 32px;\n}\n\n.stat[_ngcontent-%COMP%]   p[_ngcontent-%COMP%] {\n  font-size: 12px;\n  color: #90a4ae;\n}\n\n.bottom-stat[_ngcontent-%COMP%] {\n  margin-top: 30px;\n}\n\n.scroll-down[_ngcontent-%COMP%] {\n  margin-top: 30px;\n  font-size: 24px;\n}\n\n\n.purpose-section[_ngcontent-%COMP%] {\n  background: #f3efe8;\n  padding: 80px 20px;\n  text-align: center;\n}\n\n.purpose-header[_ngcontent-%COMP%]   .badge[_ngcontent-%COMP%] {\n  background: #d1fae5;\n  color: #065f46;\n  padding: 6px 14px;\n  border-radius: 20px;\n  font-size: 12px;\n}\n\n.purpose-header[_ngcontent-%COMP%]   h2[_ngcontent-%COMP%] {\n  font-size: 40px;\n  margin: 20px 0;\n  color:black;\n}\n\n.purpose-header[_ngcontent-%COMP%]   p[_ngcontent-%COMP%] {\n  max-width: 700px;\n  margin: auto;\n  color: #6b7280;\n}\n\n.purpose-cards[_ngcontent-%COMP%] {\n  display: flex;\n  justify-content: center;\n  gap: 25px;\n  margin-top: 40px;\n  flex-wrap: wrap;\n}\n\n.purpose-cards[_ngcontent-%COMP%]   .card[_ngcontent-%COMP%] {\n  background: white;\n  padding: 30px;\n  border-radius: 20px;\n  width: 300px;\n  text-align: center;\n}\n\n.purpose-cards[_ngcontent-%COMP%]   .icon[_ngcontent-%COMP%] {\n  font-size: 28px;\n  margin-bottom: 10px;\n}\n\n\n.tools-section[_ngcontent-%COMP%] {\n  background: black;\n}\n\n.tools-section[_ngcontent-%COMP%]   .badge[_ngcontent-%COMP%] {\n  background: #d1fae5;\n  color: #065f46;\n  padding: 6px 14px;\n  border-radius: 20px;\n  font-size: 12px;\n}\n\n.tools-section[_ngcontent-%COMP%]   h2[_ngcontent-%COMP%] {\n  font-size: 36px;\n  margin: 10px 0;\n}\n\n.subtitle[_ngcontent-%COMP%] {\n  color: #64748b;\n  margin-bottom: 40px;\n}\n\n.grid[_ngcontent-%COMP%] {\n  display: grid;\n  grid-template-columns: repeat(3, 1fr);\n  gap: 25px;\n}\n\n\n.tools-section[_ngcontent-%COMP%]   .card[_ngcontent-%COMP%] {\n  width: 100%;\n  padding: 25px;\n  border-radius: 16px;\n  text-align: left;\n  background: white;\n  border: 1px solid #e5e7eb;\n  transition: 0.3s;\n}\n\n.tools-section[_ngcontent-%COMP%]   .card[_ngcontent-%COMP%]:hover {\n  transform: translateY(-5px);\n}\n\n.card[_ngcontent-%COMP%]   h4[_ngcontent-%COMP%] {\n  font-size: 12px;\n  margin-bottom: 8px;\n  letter-spacing: 1px;\n  color: black;\n}\n\n.card[_ngcontent-%COMP%]   h3[_ngcontent-%COMP%] {\n  margin-bottom: 10px;\n  color:black\n}\n\n.card[_ngcontent-%COMP%]   p[_ngcontent-%COMP%] {\n  font-size: 14px;\n  color: #6b7280;\n}\n\n\n.green[_ngcontent-%COMP%] { background: #e6f4ea; }\n.yellow[_ngcontent-%COMP%] { background: #fef3c7; }\n.blue[_ngcontent-%COMP%] { background: #e0ecff; }\n.red[_ngcontent-%COMP%] { background: #fde2e2; }\n.purple[_ngcontent-%COMP%] { background: #ede9fe; }\n.green2[_ngcontent-%COMP%] { background: #e6f7f1; }\n\n\n\n@media (max-width: 768px) {\n  .grid[_ngcontent-%COMP%] {\n    grid-template-columns: 1fr;\n  }\n\n  .team-grid[_ngcontent-%COMP%] {\n    flex-direction: column;\n    align-items: center;\n  }\n\n  .stats[_ngcontent-%COMP%] {\n    flex-direction: column;\n    gap: 20px;\n  }\n}"] });
}
(() => { (typeof ngDevMode === "undefined" || ngDevMode) && i0.ɵsetClassMetadata(AboutComponent, [{
        type: Component,
        args: [{ selector: 'app-about', imports: [Layout], standalone: true, template: "<app-layout>\n  <section class=\"about-section\">\n    <div class=\"circle-bg\"></div>\n\n    <div class=\"content\">\n      <div class=\"badge\">\u25CF ABOUT BIDESH PADHNA</div>\n\n      <h1>\n        We exist so <span>no Nepali student</span><br />\n        has to figure it out alone.\n      </h1>\n\n      <p class=\"description\">\n        Bidesh Padhna was born from a simple truth \u2014 studying abroad is life-changing,\n        but the process is confusing, expensive, and lonely. We fix that. For free.\n      </p>\n\n      <div class=\"stats\">\n        <div class=\"stat\">\n          <h2>800+</h2>\n          <p>STUDENTS GUIDED</p>\n        </div>\n\n        <div class=\"stat\">\n          <h2>8</h2>\n          <p>COUNTRIES COVERED</p>\n        </div>\n\n        <div class=\"stat\">\n          <h2>94%</h2>\n          <p>VISA SUCCESS RATE</p>\n        </div>\n      </div>\n\n      <div class=\"bottom-stat\">\n        <h2>1200+</h2>\n        <p>UNIVERSITIES LISTED</p>\n      </div>\n\n      <div class=\"scroll-down\">\u2193</div>\n    </div>\n  </section>\n  <section class=\"purpose-section\">\n    <div class=\"purpose-header\">\n      <span class=\"badge\">OUR PURPOSE</span>\n      <h2>Why does Bidesh Padhna exist?</h2>\n      <p>\n        Too many bright Nepali students give up on studying abroad because the\n        process feels impossible. We built the platform we wished existed when we\n        were students.\n      </p>\n    </div>\n\n    <div class=\"purpose-cards\">\n      <div class=\"card\">\n        <div class=\"icon\">\u23F1\uFE0F</div>\n        <h3>Eliminate confusion</h3>\n        <p>\n          The path from \"I want to study abroad\" to \"I have my visa\" has 40+ steps.\n        </p>\n      </div>\n\n      <div class=\"card highlight\">\n        <div class=\"icon\">\uD83D\uDCB0</div>\n        <h3>Make it free</h3>\n        <p>\n          Consultancy fees in Nepal can cost NPR 50,000\u20132,00,000.\n        </p>\n      </div>\n\n      <div class=\"card\">\n        <div class=\"icon\">\uD83E\uDD1D</div>\n        <h3>Build community</h3>\n        <p>\n          Connect with Nepali students already studying abroad.\n        </p>\n      </div>\n    </div>\n  </section>\n  <section class=\"tools-section\">\n    <div class=\"container\">\n\n      <span class=\"badge\">EXPLORE THE PLATFORM</span>\n      <h2>Everything you can do here</h2>\n      <p class=\"subtitle\">\n        Six powerful tools, all free, all built for Nepali students going abroad.\n      </p>\n\n      <div class=\"grid\">\n\n        <div class=\"card green\">\n          <h4>JOURNEY</h4>\n          <h3>Step-by-step roadmap</h3>\n        </div>\n\n        <div class=\"card yellow\">\n          <h4>SMART TOOLS</h4>\n          <h3>AI SOP maker</h3>\n        </div>\n\n        <div class=\"card blue\">\n          <h4>UNIVERSITIES</h4>\n          <h3>University finder</h3>\n        </div>\n\n        <div class=\"card red\">\n          <h4>FINANCE</h4>\n          <h3>Cost of living calculator</h3>\n        </div>\n\n        <div class=\"card purple\">\n          <h4>CHECKLISTS</h4>\n          <h3>Document checklists</h3>\n        </div>\n\n        <div class=\"card green2\">\n          <h4>COMMUNITY</h4>\n          <h3>Student forum</h3>\n        </div>\n\n      </div>\n    </div>\n  </section>\n  \n\n</app-layout>", styles: ["body {\n  margin: 0;\n  font-family: 'Inter', sans-serif;\n}\n\n.container {\n  max-width: 1100px;\n  margin: 0 auto;\n  padding: 80px 20px;\n  text-align: center;\n}\n\n/* ABOUT SECTION */\n.about-section {\n  position: relative;\n  height: 100vh;\n  background: #0b1c2c;\n  display: flex;\n  justify-content: center;\n  align-items: center;\n  overflow: hidden;\n  color: white;\n  text-align: center;\n}\n\n.circle-bg {\n  position: absolute;\n  width: 900px;\n  height: 900px;\n  background: radial-gradient(circle, rgba(0, 255, 200, 0.15), transparent 70%);\n  border-radius: 50%;\n  z-index: 0;\n}\n\n.about-section .content {\n  position: relative;\n  z-index: 1;\n  max-width: 900px;\n}\n\n.about-section .badge {\n  display: inline-block;\n  padding: 6px 16px;\n  border-radius: 20px;\n  background: rgba(0, 255, 200, 0.1);\n  color: #00d4aa;\n  font-size: 12px;\n  margin-bottom: 20px;\n  letter-spacing: 1px;\n}\n\n.about-section h1 {\n  font-size: 48px;\n  line-height: 1.3;\n}\n\n.about-section h1 span {\n  color: #00d4aa;\n}\n\n.description {\n  margin: 20px 0;\n  color: #b0bec5;\n}\n\n.stats {\n  display: flex;\n  justify-content: center;\n  gap: 60px;\n  margin-top: 30px;\n}\n\n.stat h2 {\n  font-size: 32px;\n}\n\n.stat p {\n  font-size: 12px;\n  color: #90a4ae;\n}\n\n.bottom-stat {\n  margin-top: 30px;\n}\n\n.scroll-down {\n  margin-top: 30px;\n  font-size: 24px;\n}\n\n/* PURPOSE SECTION */\n.purpose-section {\n  background: #f3efe8;\n  padding: 80px 20px;\n  text-align: center;\n}\n\n.purpose-header .badge {\n  background: #d1fae5;\n  color: #065f46;\n  padding: 6px 14px;\n  border-radius: 20px;\n  font-size: 12px;\n}\n\n.purpose-header h2 {\n  font-size: 40px;\n  margin: 20px 0;\n  color:black;\n}\n\n.purpose-header p {\n  max-width: 700px;\n  margin: auto;\n  color: #6b7280;\n}\n\n.purpose-cards {\n  display: flex;\n  justify-content: center;\n  gap: 25px;\n  margin-top: 40px;\n  flex-wrap: wrap;\n}\n\n.purpose-cards .card {\n  background: white;\n  padding: 30px;\n  border-radius: 20px;\n  width: 300px;\n  text-align: center;\n}\n\n.purpose-cards .icon {\n  font-size: 28px;\n  margin-bottom: 10px;\n}\n\n/* TOOLS SECTION (FIXED MAIN ISSUE) */\n.tools-section {\n  background: black;\n}\n\n.tools-section .badge {\n  background: #d1fae5;\n  color: #065f46;\n  padding: 6px 14px;\n  border-radius: 20px;\n  font-size: 12px;\n}\n\n.tools-section h2 {\n  font-size: 36px;\n  margin: 10px 0;\n}\n\n.subtitle {\n  color: #64748b;\n  margin-bottom: 40px;\n}\n\n.grid {\n  display: grid;\n  grid-template-columns: repeat(3, 1fr);\n  gap: 25px;\n}\n\n/* IMPORTANT FIX */\n.tools-section .card {\n  width: 100%;\n  padding: 25px;\n  border-radius: 16px;\n  text-align: left;\n  background: white;\n  border: 1px solid #e5e7eb;\n  transition: 0.3s;\n}\n\n.tools-section .card:hover {\n  transform: translateY(-5px);\n}\n\n.card h4 {\n  font-size: 12px;\n  margin-bottom: 8px;\n  letter-spacing: 1px;\n  color: black;\n}\n\n.card h3 {\n  margin-bottom: 10px;\n  color:black\n}\n\n.card p {\n  font-size: 14px;\n  color: #6b7280;\n}\n\n/* COLORS */\n.green { background: #e6f4ea; }\n.yellow { background: #fef3c7; }\n.blue { background: #e0ecff; }\n.red { background: #fde2e2; }\n.purple { background: #ede9fe; }\n.green2 { background: #e6f7f1; }\n\n\n/* RESPONSIVE */\n@media (max-width: 768px) {\n  .grid {\n    grid-template-columns: 1fr;\n  }\n\n  .team-grid {\n    flex-direction: column;\n    align-items: center;\n  }\n\n  .stats {\n    flex-direction: column;\n    gap: 20px;\n  }\n}"] }]
    }], () => [{ type: i1.Router }], null); })();
(() => { (typeof ngDevMode === "undefined" || ngDevMode) && i0.ɵsetClassDebugInfo(AboutComponent, { className: "AboutComponent", filePath: "src/app/pages/about /about.ts", lineNumber: 12 }); })();
